version: '3'

## TODO Melhorar a criação da imagem e container do angular. Está com tamanho grande e consumindo muita memória

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "crud"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    networks:
      - docker-network
    restart: always

  crud-api:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    container_name: crud-api
    image: wesleyeduardodev/crud-api:latest
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: test
      TZ: "America/Sao_Paulo"
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - docker-network
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 700M
    restart: always

  crud-angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: wesleyeduardodev/crud-angular
    container_name: crud-angular
    ports:
      - "4200:4200"
    depends_on:
      - crud-api
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge