version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "crud"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    #volumes:
      #-  ../postgres-data:/var/lib/postgresql/data
    networks:
      - docker-network
    restart: always

  crud-api:
    container_name: crud-api
    image: wesleyeduardodev/crud-api:latest
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 3000
      TZ: "America/Sao_Paulo"
    ports:
      - "8080:3000"
    depends_on:
      - postgres-db
    networks:
      - docker-network
    restart: always

networks:
  docker-network:
    driver: bridge