version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "crud"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    #volumes:
      #-  ../postgres-data:/var/lib/postgresql/data
    networks:
      - docker-network
    restart: always

networks:
  docker-network:
    driver: bridge