version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "crud"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    networks:
      - docker-network
    restart: always

  crud-api:
    container_name: crud-api
    image: wesleyeduardodev/crud-api:latest
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: prod
      TZ: "America/Sao_Paulo"
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - docker-network
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 700M
    restart: always

networks:
  docker-network:
    driver: bridge