version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "thehome"
      TZ: "America/Sao_Paulo"
    ports:
      - "15432:5432"
    networks:
      - docker-network
    restart: always

  thehome-api:
    container_name: thehome-api
    image: wesleyeduardodev/thehome-api:latest
    environment:
      SERVER_PORT: 3000
      SPRING_PROFILES_ACTIVE: prod
      TZ: "America/Sao_Paulo"
    ports:
      - "80:3000"
    depends_on:
      - postgres-db
    networks:
      - docker-network
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 700M
    restart: always

      #thehome-angular:
      #image: wesleyeduardodev/thehome-angular:latest
      #container_name: thehome-angular-container
      #ports:
      #  - "4200:4200"
      #depends_on:
      # - thehome-api
      #networks:
    # - docker-network

networks:
  docker-network:
    driver: bridge