server:
  port: ${SERVER_PORT}

spring:
  application:
    name: "crud-api"

  config:
    activate:
      on-profile:
        - prod

  datasource:
    url: jdbc:postgresql://postgres-db:5432/crud?currentSchema=public
    username: "postgres"
    password: "root"
    driver-class-name: "org.postgresql.Driver"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: "/crud-api/swagger-ui.html"

crud:
  api:
    user: admin
    password: admin