server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crud
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

crud:
  api:
    user: admin
    password: admin

springdoc:
  swagger-ui:
    operations-sorter: method
    path: "/crud-api/swagger-ui.html"
